name: Actualizar Precios Bonos

on:
  schedule:
    # Correr a las 15:30 UTC (12:30 ARG) y 20:30 UTC (17:30 ARG) de Lunes a Viernes
    - cron: '30 15,20 * * 1-5'
  workflow_dispatch:

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Chequear código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Instalar Librerías
        run: |
          pip install -r requirements.txt

      - name: Correr Script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python scripts/actualizar_bonos.py
